Add item requests
katja-balakireva/java-shareit pull request #5
Opened 2022-12-03 10:43 UTC by katja-balakireva

2022-12-03 17:15 UTC, kukolev requested changes

2022-12-03 17:15 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +                .id(bookingDto.getId()) //?
Этот комментарий никак не помогает анализировать код. Бесполезные комментарии нужно удалять, чтобы не мешали.

2022-12-03 17:15 UTC, kukolev commented on src/main/java/ru/practicum/shareit/request/RequestServiceImpl.java
> +            log.warn("id пользователя не может быть отрицательным: {}", userId);
Формулировка лога некорректная, т.к. userId может быть равен нулю. Думаю стоит это поправить или поправить условие.

2022-12-03 17:15 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/BookingMapperTest.java
> +    BookingMapper bookingMapper;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-12-03 17:15 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTest.java
> +    void testAddBooking() {
Этот тест нужно разбить на несколько небольших тестов, каждый из которых проверяет что-то конкретное. Хороший юнит тест состоит из трех блоков кода:

1. Подготовка данных для теста
2. Вызов тестируемого метода
3. Проверка результатов

Важно, чтобы п.2 выполнялся однократно - так будет проще понять что пошло не так, если один или несколько тестов упадут.

Подробнее о хороших практиках юнит-тестирования можно прочитать тут:  https://www.baeldung.com/java-unit-testing-best-practices

Также нужно поправить и другие подобные тесты.

2022-12-03 17:57 UTC, katja-balakireva commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTest.java
> +    void testAddBooking() {
Спасибо за материал, ознакомлюсь и всё поправлю 👌

2022-12-04 19:44 UTC, kukolev requested changes

2022-12-04 19:44 UTC, kukolev commented on src/test/java/ru/practicum/shareit/item/CommentMapperTest.java
> +    User testAuthor;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-12-04 19:44 UTC, kukolev commented on src/test/java/ru/practicum/shareit/item/ItemServiceTest.java
> +    void testAddCommentFailedValidations() {
Не исправлено замечание: https://github.com/katja-balakireva/java-shareit/pull/5#discussion_r1038809531

Этот тест нужно разбить на три.

2022-12-04 19:44 UTC, kukolev commented on src/test/java/ru/practicum/shareit/request/RequestServiceTest.java
> +    void testAddItemRequestFailedValidations() {
Не исправлено замечание https://github.com/katja-balakireva/java-shareit/pull/5#discussion_r1038809531

Этот тест нужно разбить на два.

2022-12-04 19:44 UTC, kukolev commented on src/test/java/ru/practicum/shareit/request/RequestServiceTest.java
> +    void testAddItemRequestNoItemsFailedValidations() {
Не исправлено замечание https://github.com/katja-balakireva/java-shareit/pull/5#discussion_r1038809531

Этот тест нужно разбить на два.

2022-12-04 19:44 UTC, kukolev commented on src/test/java/ru/practicum/shareit/request/RequestServiceTest.java
> +    void testGetByRequestIdFailedValidations() {
Не исправлено замечание https://github.com/katja-balakireva/java-shareit/pull/5#discussion_r1038809531

Этот тест нужно разбить на три.

2022-12-04 19:44 UTC, kukolev commented on src/test/java/ru/practicum/shareit/request/RequestServiceTest.java
> +    void testGetAllRequestsNotOwnerFailedValidations() {
Не исправлено замечание https://github.com/katja-balakireva/java-shareit/pull/5#discussion_r1038809531

Этот тест нужно разбить на два.

2022-12-05 16:38 UTC, kukolev approved these changes

2022-12-05 17:40 UTC, merged